# Generated by Django 3.2.20 on 2024-11-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_id_alter_productgallery_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabricante',
            field=models.CharField(default='Rodman', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='puerto',
            field=models.CharField(default='Santa Maria', max_length=100),
        ),
    ]
