# Generated by Django 3.2.20 on 2024-11-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacidad',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
