# Generated by Django 3.2.20 on 2024-12-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_fabricante_puerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.fabricante'),
        ),
        migrations.AlterField(
            model_name='product',
            name='puerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.puerto'),
        ),
    ]
