# Generated by Django 5.1.3 on 2024-11-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaBarco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Barco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("imagen", models.ImageField(upload_to="imagenes_barcos/")),
                ("disponibilidad", models.BooleanField(default=True)),
                ("tarifa_diaria", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="barcos.categoriabarco",
                    ),
                ),
            ],
        ),
    ]
