# Generated by Django 3.2.20 on 2024-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_id_alter_cartitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
