# Generated by Django 5.1.3 on 2024-11-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("barcos", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alquiler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de pago"),
                            ("PAGADO", "Pagado"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("fianza", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tarifa_combustible",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "barco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="barcos.barco"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.perfilusuario",
                    ),
                ),
            ],
        ),
    ]
