version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/hundidos/db
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1  # Puedes ajustar según sea necesario
      - DJANGO_SETTINGS_MODULE=hundidos.settings
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  sqlite_data:
